### ISSUE TITLE
Get random number when button is clicked

### ISSUE THREAD

**Issue by bernardo5** [bernardo5/RandomChoices#2]
## Description

When the random button is hit, a random number should be generated and a Movie/Book should be displayed accordingly.

## Tasks

* [ ] Create hardcoded books/movies in array

* [ ] Simulate correct functioning with hardcoded values

* [ ] display result in popup from #1
